// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Sep  1 21:49:58 2008

#include <wx/wx.h>
#include <wx/image.h>

#ifndef INITMEMORIES_H
#define INITMEMORIES_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class InitMemories: public wxFrame {
public:
    // begin wxGlade: InitMemories::ids
    // end wxGlade

    InitMemories(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: InitMemories::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    void onTimerMDEvent(wxCommandEvent &event);
    void onTimerMPEvent(wxCommandEvent &event);
    void onApplyClick(wxCommandEvent &event);
    void onConfigureClick(wxCommandEvent &event);
    void onCancelClick(wxCommandEvent &event);
    void onInitMDClick(wxCommandEvent &event);
    void onThreeOPTClick(wxCommandEvent &event);
    void onSubGClick(wxCommandEvent &event);
    void onInitMPClick(wxCommandEvent &event);
    void onLSClick(wxCommandEvent &event);
    void onPertClick(wxCommandEvent &event);
    void onConsClick(wxCommandEvent &event);

protected:
    // begin wxGlade: InitMemories::attributes
    wxStatusBar* init_memories_statusbar;
    wxButton* apply_button;
    wxButton* configure_button;
    wxButton* cancel_button;
    wxStaticLine* top_static_line;
    wxButton* init_md_button;
    wxGauge* init_md_gauge;
    wxButton* three_opt_button;
    wxComboBox* three_opt_combo_box;
    wxButton* subg_button;
    wxComboBox* subg_combo_box;
    wxStaticLine* mid_static_line;
    wxButton* init_mp_button;
    wxGauge* init_mp_gauge;
    wxButton* ls_button;
    wxComboBox* ls_combo_box;
    wxButton* pert_button;
    wxComboBox* pert_combo_box;
    wxButton* cons_button;
    wxComboBox* cons_combo_box;
    // end wxGlade
}; // wxGlade: end class


#endif // INITMEMORIES_H
